### ISSUE TITLE
[FEEDBACK] Collaboration Learning Track

### ISSUE THREAD

**Issue by JackLot** [JackLot/LearnGit.io#22]
Lessons covering Git collaboration will start releasing late February into March 2024. Topics covered will include:

- [x] Collaboration theory, and the fundamentals of remote repositories
- [x] Connecting to remote repositories using SSH
- [x] Cloning
- [x] Fetching
- [x] Pushing
- [x] Pulling
- [x] Remote tracking branches
- [x] Pull requests / code review
- [x] Force push and manual remote repository setup

Looking for feedback on these topics, and others that may fit into this learning track. The goal of these lessons is for learners to feel confident using Git's remote collaboration features within a team.

**Comment by dhavalsavalia** [comment]
This is great!

**Comment by JackLot** [comment]
The first module has been released.

**Comment by JackLot** [comment]
Second module has been released covering clone, fetch, push, pull. I will need to pivot for the next few weeks to prepare LearnGit.io for public release, but I expect to finish the last few lessons of this module by early/mid May. My current plan is to cover pull requests, remote tracking branches and force push in the final lessons.

**Comment by JackLot** [comment]
A quick update on this track: The rest of the lessons will be released in May, this got a bit delayed with other work related to launching LearnGit.io.

**Comment by JackLot** [comment]
The last 2 modules are now complete. I still need to finish writing the lesson text; however, the modules will be released next week to close out this learning track.

**Comment by JackLot** [comment]
This learning track is now live
