### ISSUE TITLE
Add course Progress Tracker

### ISSUE THREAD

**Issue by KeshariPiyush24** [JackLot/LearnGit.io#39]
It would be very beneficial if course progress is tracked.

**Comment by KeshariPiyush24** [comment]
@JackLot on a sidenote, if you want I can collaborate to work on this feature without anything in return.

**Comment by JackLot** [comment]
+1 for this feature via email

**Comment by JackLot** [comment]
Realize this is being track by https://github.com/JackLot/LearnGit.io/issues/19. Closing as duplicate
