### ISSUE TITLE
[BUG] Rebase Theory Videos duplication

### ISSUE THREAD

**Issue by KeshariPiyush24** [JackLot/LearnGit.io#41]
**Describe the bug**
If you observe closely, The Introduction video for "1. Rebase Fundamentals" and "2. Advanced Rebase" are same. The video currently suits only for the "2. Advanced Rebase" as it talks about the rewriting commit history part of the rebase which suits the "2nd" module but I believe there should be another introduction video for the "1st" section. Also the video for the "1st" section is broken down into sub parts but not in the "2nd" one. Please address these two bugs.

**To Reproduce**
1. Go to '[Rebase Deconstructed](https://app.learngit.io/courses/rebase-deconstructed/)' section
2. Click on the 1st videos for both the lessons.

**Expected behavior**
A new intro video for the 1st lesson should be there which talks about the rebasing branch part of the rebase command.

**Screenshots**
![Screenshot 2024-09-15 at 7 36 36 PM](https://github.com/user-attachments/assets/0f712219-24c5-4191-a6da-028de3f1bff9)

**Computing environment**
Agnostic to platform.

**Additional context**
N/A

**Comment by JackLot** [comment]
Wow, great catch. I must have mixed up the clips. I will get this fixed and update this ticket when complete.

**Comment by JackLot** [comment]
This is now fixed. Thank you for flagging this!
